version: '3.8'
services:
  db:
    container_name: charlie-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dev-db:/var/lib/postgresql/data

  instance1:
    container_name: charlie-instance-1
    image: tomcat:9-jdk11
    ports:
      - '8000:8080'
    environment:
      DB_HOST: db
    volumes:
      - ./build/libs/sys-charlie-0.0.1.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
        - db

  instance2:
    container_name: charlie-instance-2
    image: tomcat:9-jdk11
    ports:
      - '9000:8080'
    environment:
      DB_HOST: db
    volumes:
      - ./build/libs/sys-charlie-0.0.1.war:/usr/local/tomcat/webapps/ROOT.war
    depends_on:
      - db

  nginx:
    container_name: charlie-load-balancer
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db
      - instance1
      - instance2
